name:                gameoflife
version:             0.1.0.0
github:              "patriques82/gameoflife"
license:             BSD3
author:              "Patrik Nygren"
maintainer:          "patriknygren82@gmail.com"
copyright:           "2019 Patrik Nygren"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gameoflife#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split

library:
  source-dirs: src

executables:
  gameoflife-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameoflife

tests:
  gameoflife-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gameoflife
    - hspec
    - hspec-contrib
    - HUnit
